language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shadisabagh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shadisabagh/docker-react npm run test